_target_: src.models.cifar10_module.CifarLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: timm.create_model
  model_name: resnet50  # This will get overridden from model_name (eg: resnet18) passed from /configs/experiment/cifar_timm.yaml
  pretrained: True
  num_classes: 10